//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receita01.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_receitas
    {
        public int id { get; set; }
        public string nome_receita { get; set; }
        public string estilo { get; set; }
        public string receita_text { get; set; }
    }
}
